services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: task_api
      POSTGRES_USER: anushka
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U anushka  -d task_api"]
      interval: 5s
      timeout: 5s
      retries: 5
  task-api:
    build: .
    depends_on: 
      postgres:
        condition: service_healthy

    environment:
      - DATABASE_URL=postgresql+psycopg://anushka:password@postgres:5432/task_api
    ports:
      - "8000:8000"

  frontend:
    build: 
      context: ./frontend
    ports:
      - "5500:80"
